### ISSUE TITLE
Map Icons sometimes shipping with transparent box

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#409] opened 2023-12-05 14:57 UTC
![PXL_20231205_142938317](https://github.com/MIT-CAVE/cave_static/assets/32932187/043a9a73-14f7-40be-aea3-64f56f6fbb36)

@mitrussell found this on one of our apps when the app was open on two screens. Not sure if it is related to two screens.

**Comment by connor-makowski** [comment] 2023-12-05 15:13
This is happening on 2.0.3 - I am able to recreate on my side.

**Comment by mitrussell** [comment] 2023-12-05 15:14
This happened in the CAVE Lab. The new Win 11 server has three screens, but the app was only open in one tab on a single screen (wall). I cannot reproduce on my laptop.

**Comment by mrkwanzaa** [comment] 2023-12-05 22:13
The above commit fixes this issue but causes icons much larger than 50px to become blurry (previously this value was a much more reasonable 250px). I'm going to close this issue so we can make a new one for fixing the blurriness down the road, but we should make sure to link this issue when that one is created.

**Closed by mrkwanzaa** 2023-12-05 22:13 UTC
