### ISSUE TITLE
`timeObject` values are not rendered correctly in map modals

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#215] opened 2023-04-13 18:10 UTC

**Comment by connor-makowski** [comment] 2023-04-13 19:43
This only appears to be happening when the full time object array is all `0.0`. Otherwise it appears to work.

**Comment by mrkwanzaa** [comment] 2023-04-14 16:57
@connor-makowski I have a fix for this worked out. The issue is marked `1.3.x`, do we want to do the fix in a `1.3` branch or just in `1.4-dev`?

**Comment by connor-makowski** [comment] 2023-04-14 17:09
@mrkwanzaa This should be in 1.3.4-dev (as we need it currently and it is not a feature).

**Comment by luisvasq** [comment] 2023-04-14 17:15
Hey guys, I haven't merged `1.3.3-dev` yet, so @mrkwanzaa could also use this branch to push the fix, unless you prefer to have a new iteration, @connor-makowski (?).

**Closed** 2023-04-14 17:44 UTC
